output_root: "outputs"
output_version: "baseline"
backup_name: "weights"
log_name: "logs"

#labels: ["1","2","3","4","5","6","77","bike","bus","car","motor","person","rider","traffic light","traffic light-amber","traffic light-green","traffic light-red","traffic sign","train","truck"]
labels: ["bike","bus","car","motor","person","rider","traffic light","traffic light-amber","traffic light-green","traffic light-red","traffic sign","train","truck"]


data_root_dir: "VOCdevkitCOCO/onedet_cache"

train:
    dataset: "train"
    stdout: True
    gpus: "0"
    nworkers: 16
    pin_mem: True

    momentum: 0.9
    decay: 0.0005

    clear: False

    warmup_lr: 0.00005
    lr_steps: [400,700,900,1000, 25000,30000, 35000]
    lr_rates: [0.0001,0.0002,0.0005,0.001, 0.0001,0.00001,0.000001]
    max_batches: 60200
    resize_interval: 10

    backup_interval: 200
    backup_steps: [1000]
    backup_rates: [10000]

    input_shape: [416, 416]
    batch_size: 64
    mini_batch_size: 4
    weights: "outputs/Yolov3/baseline/weights/weights_30000.pt"

test:
    dataset: "test"
    stdout: True
    gpus: "0"
    nworkers: 8
    pin_mem: True

    input_shape: [544, 544]
    batch_size: 8
    weights: "outputs/Yolov3/baseline/weights/backup.pt"

    conf_thresh: 0.4
    nms_thresh: 0.95

    results: "results"

speed:
    gpus: "0"
    batch_size: 1
    max_iters: 200
    input_shape: [416, 416]
